name: '[builder] CI for releases'

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v2
        -
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
        -
            name: Set up Docker Buildx
            id: buildx
            uses: crazy-max/ghaction-docker-buildx@v3
            with:
                buildx-version: latest
                qemu-version: latest
        -
            name: Available platforms
            run: echo ${{ steps.buildx.outputs.platforms }}
        -
            name: Build dockerfile (with push)
            run: |
                docker buildx build \
                --platform=linux/arm/v6,linux/arm/v7 \
                --output "type=image,push=true" \
                --file ./Dockerfile . \
                --tag fsegouin/osbacnet:latest
